import { DocumentRecord, Evidence, Transaction } from '../src/types';

export interface GoldenSample {
  document: DocumentRecord;
  evidence: Evidence[];
  transactions: Transaction[];
  rawText: string;
}

const USER_ID = 'usr_bangladesh_consumer_01';

export const GOLDEN_SAMPLES: Record<string, GoldenSample> = {
  sample_bkash: {
    document: {
      id: 'doc_bkash_sep2026',
      upload_id: 'upl_bkash_sep2026',
      user_id: USER_ID,
      filename: 'bKash_Statement_Sep2026.pdf',
      document_type: 'MOBILE_MONEY_STATEMENT',
      source_type: 'bKash',
      language: 'mixed',
      page_count: 2,
      status: 'PROCESSED',
      file_size: 148200,
      mime_type: 'application/pdf',
      created_at: '2026-09-02T10:15:00Z',
    },
    rawText: `
bKash Limited - Customer Statement
Account: 01711****92
Period: 01 Sep 2026 to 18 Sep 2026
Currency: BDT (৳)

Date       TrxID       Description / Counterparty       Amount (BDT)   Type
----------------------------------------------------------------------------
2026-09-01 9H8K2L1M   Monthly Salary Remittance       +75,000.00    Credit
2026-09-02 9H8K3A2F   Payment to Foodpanda FP*DHK9382     -680.00    Debit
2026-09-03 9H8K4B3G   DESCO Electricity Bill Token       -2,450.00   Debit
2026-09-04 9H8K5C4H   Payment to Chaldal Limited         -3,890.00   Debit
2026-09-05 9H8K6D5I   Uber BD Trip Dhk                   -340.00    Debit
2026-09-06 9H8K7E6J   Grameenphone Flexiload             -599.00    Debit
2026-09-07 9H8K8F7K   Payment to Foodpanda FP*DHK9382     -520.00    Debit
2026-09-08 9H8K9G8L   Titas Gas Transmission Bill          -650.00    Debit
2026-09-09 9H8L1H9M   Dhaka Metro Rail MRT Pass Recharge   -500.00    Debit
2026-09-10 9H8L2I1N   Payment to Shwapno Dhanmondi       -4,120.00   Debit
2026-09-11 9H8L3J2P   Pathao Ride Commute                -180.00    Debit
2026-09-12 9H8L4K3Q   Payment to Foodpanda FP*DHK9382     -840.00    Debit
2026-09-13 9H8L5L4R   Lazz Pharma Dhanmondi              -1,250.00   Debit
2026-09-14 9H8L6M5S   Link3 Broadband Internet Bill      -1,500.00   Debit
2026-09-15 9H8L7N6T   Uber BD Trip Banani                -420.00    Debit
2026-09-16 9H8L8O7U   Foodpanda FP*DHK9382                -460.00    Debit
2026-09-17 9H8L9P8V   Send Money to 01819****33 (Rent)  -18,000.00   Debit
2026-09-18 9H8M1Q9W   Foodpanda FP*DHK9382                -730.00    Debit
    `,
    evidence: [
      {
        id: 'ev_bkash_01',
        document_id: 'doc_bkash_sep2026',
        page_number: 1,
        bounding_box: { x: 50, y: 120, width: 700, height: 28, page: 1 },
        raw_text: '2026-09-01 9H8K2L1M Monthly Salary Remittance +75,000.00 Credit',
        normalized_text: 'Salary Remittance ৳75,000 Credit',
        evidence_type: 'AMOUNT',
        created_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'ev_bkash_02',
        document_id: 'doc_bkash_sep2026',
        page_number: 1,
        bounding_box: { x: 50, y: 152, width: 700, height: 28, page: 1 },
        raw_text: '2026-09-02 9H8K3A2F Payment to Foodpanda FP*DHK9382 -680.00 Debit',
        normalized_text: 'Foodpanda ৳680 Debit',
        evidence_type: 'MERCHANT',
        created_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'ev_bkash_03',
        document_id: 'doc_bkash_sep2026',
        page_number: 1,
        bounding_box: { x: 50, y: 184, width: 700, height: 28, page: 1 },
        raw_text: '2026-09-03 9H8K4B3G DESCO Electricity Bill Token -2,450.00 Debit',
        normalized_text: 'DESCO Electricity ৳2,450 Debit',
        evidence_type: 'AMOUNT',
        created_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'ev_bkash_04',
        document_id: 'doc_bkash_sep2026',
        page_number: 1,
        bounding_box: { x: 50, y: 216, width: 700, height: 28, page: 1 },
        raw_text: '2026-09-04 9H8K5C4H Payment to Chaldal Limited -3,890.00 Debit',
        normalized_text: 'Chaldal Groceries ৳3,890 Debit',
        evidence_type: 'AMOUNT',
        created_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'ev_bkash_05',
        document_id: 'doc_bkash_sep2026',
        page_number: 1,
        bounding_box: { x: 50, y: 248, width: 700, height: 28, page: 1 },
        raw_text: '2026-09-05 9H8K6D5I Uber BD Trip Dhk -340.00 Debit',
        normalized_text: 'Uber BD Trip ৳340 Debit',
        evidence_type: 'MERCHANT',
        created_at: '2026-09-02T10:15:00Z',
      },
    ],
    transactions: [
      {
        id: 'txn_bks_01',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-01',
        posted_at: '2026-09-01T09:00:00Z',
        amount: 75000,
        currency: 'BDT',
        direction: 'INCOME',
        merchant_name: 'Monthly Salary',
        raw_merchant_name: 'Monthly Salary Remittance',
        description: 'Payroll deposit received',
        category_id: 'cat_income',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: ['ev_bkash_01'],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.99,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_02',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-02',
        posted_at: '2026-09-02T13:42:00Z',
        amount: 680,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Foodpanda',
        raw_merchant_name: 'Foodpanda FP*DHK9382',
        description: 'Lunch delivery order',
        category_id: 'cat_food',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: ['ev_bkash_02'],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.97,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_03',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-03',
        posted_at: '2026-09-03T11:10:00Z',
        amount: 2450,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'DESCO Electricity',
        raw_merchant_name: 'DESCO Electricity Bill Token',
        description: 'Prepaid electric meter recharge',
        category_id: 'cat_bills',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: ['ev_bkash_03'],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.99,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_04',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-04',
        posted_at: '2026-09-04T18:20:00Z',
        amount: 3890,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Chaldal',
        raw_merchant_name: 'Payment to Chaldal Limited',
        description: 'Pantry and fresh groceries',
        category_id: 'cat_groceries',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: ['ev_bkash_04'],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.98,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_05',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-05',
        posted_at: '2026-09-05T08:50:00Z',
        amount: 340,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Uber BD',
        raw_merchant_name: 'Uber BD Trip Dhk',
        description: 'Morning office commute',
        category_id: 'cat_transport',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: ['ev_bkash_05'],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.96,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_06',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-06',
        posted_at: '2026-09-06T14:15:00Z',
        amount: 599,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Grameenphone',
        raw_merchant_name: 'Grameenphone Flexiload',
        description: 'Monthly data & voice combo plan',
        category_id: 'cat_mobile',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.98,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_07',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-07',
        posted_at: '2026-09-07T21:05:00Z',
        amount: 520,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Foodpanda',
        raw_merchant_name: 'Payment to Foodpanda FP*DHK9382',
        description: 'Late dinner delivery',
        category_id: 'cat_food',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.97,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_08',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-08',
        posted_at: '2026-09-08T10:30:00Z',
        amount: 650,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Titas Gas',
        raw_merchant_name: 'Titas Gas Transmission Bill',
        description: 'Residential burner gas utility',
        category_id: 'cat_bills',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.99,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_09',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-09',
        posted_at: '2026-09-09T08:15:00Z',
        amount: 500,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Dhaka Metro Rail',
        raw_merchant_name: 'Dhaka Metro Rail MRT Pass Recharge',
        description: 'Rapid pass top-up at station',
        category_id: 'cat_transport',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.98,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_10',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-10',
        posted_at: '2026-09-10T19:30:00Z',
        amount: 4120,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Shwapno Superstore',
        raw_merchant_name: 'Payment to Shwapno Dhanmondi',
        description: 'Weekly supermarket provisions',
        category_id: 'cat_groceries',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.99,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_11',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-11',
        posted_at: '2026-09-11T12:00:00Z',
        amount: 180,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Pathao',
        raw_merchant_name: 'Pathao Ride Commute',
        description: 'Bike share across Dhanmondi',
        category_id: 'cat_transport',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.95,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_12',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-12',
        posted_at: '2026-09-12T13:10:00Z',
        amount: 840,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Foodpanda',
        raw_merchant_name: 'Payment to Foodpanda FP*DHK9382',
        description: 'Family biryani lunch',
        category_id: 'cat_food',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.97,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_13',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-13',
        posted_at: '2026-09-13T17:45:00Z',
        amount: 1250,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Lazz Pharma',
        raw_merchant_name: 'Lazz Pharma Dhanmondi',
        description: 'Monthly prescription refills',
        category_id: 'cat_health',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.99,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_14',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-14',
        posted_at: '2026-09-14T10:00:00Z',
        amount: 1500,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Broadband Internet',
        raw_merchant_name: 'Link3 Broadband Internet Bill',
        description: '50 Mbps optic fiber home connection',
        category_id: 'cat_mobile',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.98,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_15',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-15',
        posted_at: '2026-09-15T09:10:00Z',
        amount: 420,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Uber BD',
        raw_merchant_name: 'Uber BD Trip Banani',
        description: 'Car ride to client meeting',
        category_id: 'cat_transport',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.96,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_16',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-16',
        posted_at: '2026-09-16T14:20:00Z',
        amount: 460,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Foodpanda',
        raw_merchant_name: 'Foodpanda FP*DHK9382',
        description: 'Afternoon coffee & bakery snacks',
        category_id: 'cat_food',
        category_source: 'MERCHANT_RULE',
        status: 'NEEDS_REVIEW', // Intentional item for Review screen!
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.82,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_17',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-17',
        posted_at: '2026-09-17T11:00:00Z',
        amount: 18000,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Apartment Landlord',
        raw_merchant_name: 'Send Money to 01819****33 (Rent)',
        description: 'Monthly flat rent transfer',
        category_id: 'cat_bills',
        category_source: 'MERCHANT_RULE',
        status: 'ACCEPTED',
        evidence_ids: [],
        // No extraction confidence. The fixture is synthetic, so no extractor
        // ever produced a score for it, and carrying the old flat 0.92 asserted
        // a certainty that never existed. The provenance records how the row
        // really came to be instead.
        provenance: {
          source: 'ENGINE_DERIVED',
          calculation_version: 'engine-1.1.0',
          derivation: 'golden fixture, not produced by extraction',
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
      {
        id: 'txn_bks_18',
        user_id: USER_ID,
        document_id: 'doc_bkash_sep2026',
        transaction_date: '2026-09-18',
        posted_at: '2026-09-18T19:40:00Z',
        amount: 730,
        currency: 'BDT',
        direction: 'EXPENSE',
        merchant_name: 'Foodpanda',
        raw_merchant_name: 'Foodpanda FP*DHK9382',
        description: 'Dinner burger meal',
        category_id: 'cat_food',
        category_source: 'MERCHANT_RULE',
        status: 'NEEDS_REVIEW', // Intentional item for Review screen!
        evidence_ids: [],
        provenance: {
          source: 'EXTRACTED',
          extraction_model: 'golden-fixture',
          extraction_version: 'v1',
          extraction_confidence: 0.84,
        },
        created_at: '2026-09-02T10:15:00Z',
        updated_at: '2026-09-02T10:15:00Z',
      },
    ],
  },
};

// Previous month transactions for comparative calculations (August 2026)
export const PREVIOUS_MONTH_SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_aug_01',
    user_id: USER_ID,
    transaction_date: '2026-08-01',
    posted_at: '2026-08-01T09:00:00Z',
    amount: 75000,
    currency: 'BDT',
    direction: 'INCOME',
    merchant_name: 'Monthly Salary',
    description: 'August Salary deposit',
    category_id: 'cat_income',
    category_source: 'MERCHANT_RULE',
    status: 'ACCEPTED',
    evidence_ids: [],
    provenance: {
      source: 'ENGINE_DERIVED',
      calculation_version: 'v1',
      derivation: 'Previous-month comparison fixture',
    },
    created_at: '2026-08-02T10:00:00Z',
    updated_at: '2026-08-02T10:00:00Z',
  },
  {
    id: 'txn_aug_02',
    user_id: USER_ID,
    transaction_date: '2026-08-03',
    posted_at: '2026-08-03T12:00:00Z',
    amount: 2200,
    currency: 'BDT',
    direction: 'EXPENSE',
    merchant_name: 'Foodpanda',
    description: 'Food delivery total in August (approx 3 orders)',
    category_id: 'cat_food',
    category_source: 'MERCHANT_RULE',
    status: 'ACCEPTED',
    evidence_ids: [],
    provenance: {
      source: 'ENGINE_DERIVED',
      calculation_version: 'v1',
      derivation: 'Previous-month comparison fixture',
    },
    created_at: '2026-08-04T10:00:00Z',
    updated_at: '2026-08-04T10:00:00Z',
  },
  {
    id: 'txn_aug_03',
    user_id: USER_ID,
    transaction_date: '2026-08-05',
    posted_at: '2026-08-05T15:00:00Z',
    amount: 7200,
    currency: 'BDT',
    direction: 'EXPENSE',
    merchant_name: 'Shwapno Superstore',
    description: 'August Groceries',
    category_id: 'cat_groceries',
    category_source: 'MERCHANT_RULE',
    status: 'ACCEPTED',
    evidence_ids: [],
    provenance: {
      source: 'ENGINE_DERIVED',
      calculation_version: 'v1',
      derivation: 'Previous-month comparison fixture',
    },
    created_at: '2026-08-06T10:00:00Z',
    updated_at: '2026-08-06T10:00:00Z',
  },
  {
    id: 'txn_aug_04',
    user_id: USER_ID,
    transaction_date: '2026-08-08',
    posted_at: '2026-08-08T10:00:00Z',
    amount: 18000,
    currency: 'BDT',
    direction: 'EXPENSE',
    merchant_name: 'Apartment Landlord',
    description: 'August Rent',
    category_id: 'cat_bills',
    category_source: 'MERCHANT_RULE',
    status: 'ACCEPTED',
    evidence_ids: [],
    provenance: {
      source: 'ENGINE_DERIVED',
      calculation_version: 'v1',
      derivation: 'Previous-month comparison fixture',
    },
    created_at: '2026-08-09T10:00:00Z',
    updated_at: '2026-08-09T10:00:00Z',
  },
  {
    id: 'txn_aug_05',
    user_id: USER_ID,
    transaction_date: '2026-08-10',
    posted_at: '2026-08-10T10:00:00Z',
    amount: 4100,
    currency: 'BDT',
    direction: 'EXPENSE',
    merchant_name: 'DESCO Electricity',
    description: 'Electricity & Gas bills',
    category_id: 'cat_bills',
    category_source: 'MERCHANT_RULE',
    status: 'ACCEPTED',
    evidence_ids: [],
    provenance: {
      source: 'ENGINE_DERIVED',
      calculation_version: 'v1',
      derivation: 'Previous-month comparison fixture',
    },
    created_at: '2026-08-11T10:00:00Z',
    updated_at: '2026-08-11T10:00:00Z',
  },
  {
    id: 'txn_aug_06',
    user_id: USER_ID,
    transaction_date: '2026-08-15',
    posted_at: '2026-08-15T10:00:00Z',
    amount: 1400,
    currency: 'BDT',
    direction: 'EXPENSE',
    merchant_name: 'Uber BD',
    description: 'Commutes in August',
    category_id: 'cat_transport',
    category_source: 'MERCHANT_RULE',
    status: 'ACCEPTED',
    evidence_ids: [],
    provenance: {
      source: 'ENGINE_DERIVED',
      calculation_version: 'v1',
      derivation: 'Previous-month comparison fixture',
    },
    created_at: '2026-08-16T10:00:00Z',
    updated_at: '2026-08-16T10:00:00Z',
  },
];
